### ISSUE TITLE
[Backend] Upbit API fetch, CoinMarketCap API fetch

### ISSUE THREAD

**Issue by mossland** [mossland/mossland_disclosure_web#1]
## Part
Backend

## DevStack
Prefer Node.js or C# (Open to using other frameworks or languages as well)

## Spec
- Fetch the MOC data below using the Upbit API or CoinMarketCap API and provide the response. (Similar to Proxy)
1. Analytics: Current Price, Price performance(24h, 1-week, 1-month, 1-year): all-time high, all-time low
2. Analytics: [Volume (24h, 1-week, 1-month)](https://docs.upbit.com/reference/%EB%B6%84minute-%EC%BA%94%EB%93%A4-1)
3. Analytics: [Volume/Market cap (24h)](https://coinmarketcap.com/currencies/moss-coin/
Circulating supply/Market cap)
4. Real-time Data: Real-time order book, [Real-time trade history](https://docs.upbit.com/docs/upbit-quotation-restful-api
)

**Comment by zootyducky** [comment]
ffbce37 done
